name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      image_name:
        type: choice
        description: "Escolha a imagem para build (node-alpine-gcloud)"
        required: true
        options:
        - node-alpine-gcloud
        default: node-alpine-gcloud
      tag:
        description: "Tag da imagem Docker"
        required: true
        default: "18"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e push da imagem Docker
      - name: Build and Push Docker Image
        run: |
          cd ${{ github.event.inputs.image_name }}
          docker build -t mikaelboffsysmo/${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag }} .
          docker push mikaelboffsysmo/${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag }}
